//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3649
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ru.nikitin.RFIDInventory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ru.nikitin.RFIDInventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string btCancel {
            get {
                return ResourceManager.GetString("btCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Закрыть.
        /// </summary>
        internal static string btCancelClose {
            get {
                return ResourceManager.GetString("btCancelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Выход.
        /// </summary>
        internal static string btCancelExit {
            get {
                return ResourceManager.GetString("btCancelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помещения.
        /// </summary>
        internal static string btCancelLocations {
            get {
                return ResourceManager.GetString("btCancelLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Описи.
        /// </summary>
        internal static string btCancelSheets {
            get {
                return ResourceManager.GetString("btCancelSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти &gt;.
        /// </summary>
        internal static string btOKEnter {
            get {
                return ResourceManager.GetString("btOKEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string btOKSearch {
            get {
                return ResourceManager.GetString("btOKSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать &gt;.
        /// </summary>
        internal static string btOKSelect {
            get {
                return ResourceManager.GetString("btOKSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        internal static string btOKStop {
            get {
                return ResourceManager.GetString("btOKStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записать.
        /// </summary>
        internal static string btOKWrite {
            get {
                return ResourceManager.GetString("btOKWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по всем описям.
        /// </summary>
        internal static string chFindAll {
            get {
                return ResourceManager.GetString("chFindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено.
        /// </summary>
        internal static string chFound {
            get {
                return ResourceManager.GetString("chFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помещение.
        /// </summary>
        internal static string chLocation {
            get {
                return ResourceManager.GetString("chLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помещения.
        /// </summary>
        internal static string chLocationsBySheetPrefix {
            get {
                return ResourceManager.GetString("chLocationsBySheetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        internal static string dgcCount {
            get {
                return ResourceManager.GetString("dgcCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string dgcLocationsName {
            get {
                return ResourceManager.GetString("dgcLocationsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инв.№, Сер.№, Номенклатура.
        /// </summary>
        internal static string dgcObjectsObject {
            get {
                return ResourceManager.GetString("dgcObjectsObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №, Дата.
        /// </summary>
        internal static string dgcSheetsNumber {
            get {
                return ResourceManager.GetString("dgcSheetsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МОЛ.
        /// </summary>
        internal static string dgcSheetsPerson {
            get {
                return ResourceManager.GetString("dgcSheetsPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Павел Никитин © 2013.
        /// </summary>
        internal static string lbAuthor {
            get {
                return ResourceManager.GetString("lbAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79257977551@mail.ru.
        /// </summary>
        internal static string lbAuthorContact {
            get {
                return ResourceManager.GetString("lbAuthorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработчик:.
        /// </summary>
        internal static string lbAuthorText {
            get {
                return ResourceManager.GetString("lbAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демонстрационная версия.
        /// </summary>
        internal static string lbDemo {
            get {
                return ResourceManager.GetString("lbDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный номер устройства:.
        /// </summary>
        internal static string lbDeviceSerialText {
            get {
                return ResourceManager.GetString("lbDeviceSerialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация:.
        /// </summary>
        internal static string lbInCompany {
            get {
                return ResourceManager.GetString("lbInCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвентарный номер:.
        /// </summary>
        internal static string lbInvNumberText {
            get {
                return ResourceManager.GetString("lbInvNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия:.
        /// </summary>
        internal static string lbLicenseText {
            get {
                return ResourceManager.GetString("lbLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор помещения:.
        /// </summary>
        internal static string lbLocationIdText {
            get {
                return ResourceManager.GetString("lbLocationIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование помещения:.
        /// </summary>
        internal static string lbNameText {
            get {
                return ResourceManager.GetString("lbNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определена.
        /// </summary>
        internal static string lbNoCompany {
            get {
                return ResourceManager.GetString("lbNoCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование номенклатуры:.
        /// </summary>
        internal static string lbNomenclaruteText {
            get {
                return ResourceManager.GetString("lbNomenclaruteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определен.
        /// </summary>
        internal static string lbNoSerial {
            get {
                return ResourceManager.GetString("lbNoSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор объекта:.
        /// </summary>
        internal static string lbObjectIdText {
            get {
                return ResourceManager.GetString("lbObjectIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль .
        /// </summary>
        internal static string lbPasswordCaption {
            get {
                return ResourceManager.GetString("lbPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Инвентаризация ОС.
        /// </summary>
        internal static string lbProgramName {
            get {
                return ResourceManager.GetString("lbProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный номер:.
        /// </summary>
        internal static string lbSerialText {
            get {
                return ResourceManager.GetString("lbSerialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string lbStateAbout {
            get {
                return ResourceManager.GetString("lbStateAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите в помещение.
        /// </summary>
        internal static string lbStateChooseLocation {
            get {
                return ResourceManager.GetString("lbStateChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите опись.
        /// </summary>
        internal static string lbStateChooseSheet {
            get {
                return ResourceManager.GetString("lbStateChooseSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка криптографии.
        /// </summary>
        internal static string lbStateCtyproException {
            get {
                return ResourceManager.GetString("lbStateCtyproException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка базы данных.
        /// </summary>
        internal static string lbStateDatabaseError {
            get {
                return ResourceManager.GetString("lbStateDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка оборудования.
        /// </summary>
        internal static string lbStateDeviceError {
            get {
                return ResourceManager.GetString("lbStateDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация....
        /// </summary>
        internal static string lbStateInit {
            get {
                return ResourceManager.GetString("lbStateInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется лицензия.
        /// </summary>
        internal static string lbStateLicenseInvalidSerial {
            get {
                return ResourceManager.GetString("lbStateLicenseInvalidSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия просрочена.
        /// </summary>
        internal static string lbStateLicenseOutOfDate {
            get {
                return ResourceManager.GetString("lbStateLicenseOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных....
        /// </summary>
        internal static string lbStateLoadData {
            get {
                return ResourceManager.GetString("lbStateLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект.
        /// </summary>
        internal static string lbStateObject {
            get {
                return ResourceManager.GetString("lbStateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканируйте объекты.
        /// </summary>
        internal static string lbStateObjectsScanning {
            get {
                return ResourceManager.GetString("lbStateObjectsScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект найден ранее.
        /// </summary>
        internal static string lbStateStateAlreadyFound {
            get {
                return ResourceManager.GetString("lbStateStateAlreadyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект найден.
        /// </summary>
        internal static string lbStateStateFound {
            get {
                return ResourceManager.GetString("lbStateStateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не загружен.
        /// </summary>
        internal static string lbStateStateNotFound {
            get {
                return ResourceManager.GetString("lbStateStateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не распознан.
        /// </summary>
        internal static string lbStateStateNotValid {
            get {
                return ResourceManager.GetString("lbStateStateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метка не найдена.
        /// </summary>
        internal static string lbStateTagNotFound {
            get {
                return ResourceManager.GetString("lbStateTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка записи.
        /// </summary>
        internal static string lbStateWriteError {
            get {
                return ResourceManager.GetString("lbStateWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метка записана.
        /// </summary>
        internal static string lbStateWriteSuccessful {
            get {
                return ResourceManager.GetString("lbStateWriteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия 1.2.
        /// </summary>
        internal static string lbVersion {
            get {
                return ResourceManager.GetString("lbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибочный пароль.
        /// </summary>
        internal static string lbWrongPassword {
            get {
                return ResourceManager.GetString("lbWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///
        ///  &lt;!-- Inventory data set structure --&gt;
        ///  &lt;xs:element name=&quot;InventoryDataSet&quot; msdata:IsDataSet=&quot;true&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:choice maxOccurs=&quot;unbounded&quot;&gt;
        ///
        ///        &lt;!-- Parameters --&gt;
        ///        &lt;xs:element name=&quot;Parameters&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///
        ///              &lt;!-- Company identificator encoded  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помещения.
        /// </summary>
        internal static string tpLocations {
            get {
                return ResourceManager.GetString("tpLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты.
        /// </summary>
        internal static string tpObjects {
            get {
                return ResourceManager.GetString("tpObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описи.
        /// </summary>
        internal static string tpSheets {
            get {
                return ResourceManager.GetString("tpSheets", resourceCulture);
            }
        }
    }
}
